name: Make Test Zip 

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # this workflow has one job 
  build:
     # The type of runner that the job will run on
     runs-on: ubuntu-latest  
     defaults:
      run:
        shell: bash
        working-directory: ${{ github.workspace }}/   
     # Steps represent a sequence of tasks that will be executed as part of the job
     steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      # Runs a set of commands using the runners shell
      - name: Delete files & folders that we don't want in the flash file
        run: |
          rm LICENSE
          rm README.md
          rm -r .github
          rm -rf .git
      # Upload Boot Animation Uninstaller 
      - uses: actions/upload-artifact@v3
        with:
          name: BootAnimationUninstaller
          path: /${{ github.workspace }}/
